GET http://localhost:4004/odata/v4/vob/workFlowFunction(vob_id='b261f18b-bba6-421f-8b1f-74605d702b98',level='2',app_rej_by='dhanush.k@peolsolutions.com',status='Rejected') HTTP/1.1
Host: localhost:4004
